name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript into Javascript
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build artifact
        run: npm run bundle

      - name: Upload artifact
        # https://github.com/actions/upload-artifact
        # upload-artifact@v4+ is not currently supported on GHES yet. If you are on GHES, you must use v3.
        # Artifacts are retained for 90 days by default. You can specify a shorter retention period using the retention-days input
        uses: actions/upload-artifact@v4
        with:
          name: revolver-${{ github.sha }}.zip
          path: dist
          overwrite: true
